version: "3"
services:
  app:
    container_name: city-report-server-app
    build: ./
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: city-report-server-mongo
    image: mongo
    # https://github.com/docker/for-win/issues/138
    #volumes:
    #  - ./mongodb-data:/data/db
    ports:
      - "27017:27017"